load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_push")
load("@rules_python//python:defs.bzl", "py_binary")

load("@rules_python//python:packaging.bzl", "py_layer")

py_binary(
    name = "handler_with_deps",
    srcs = glob(
        ["*.py"],
        exclude = [
            "build_engines.py",
            "download_base_model.py",
        ],
    ),
    main = "rp_handler.py",
    python_version = "PY3",
    deps = [
        "@pip//runpod",
        "@pip//fastapi",
        "@pip//gradio",
        "@pip//pillow",
        "@pip//torch",
        "@pip//numpy",
        "@pip//opencv_python",
    ],
)

py_layer(
    name = "handler_layer",
    dep = ":handler_with_deps",
    base = "//app",
)

pkg_tar(
    name = "app_layer",
    srcs = glob([
        "*.sh",
        "*.md",
        "requirements.lock",
        "requirements.txt",
    ]),
    package_dir = "/app",
)

pkg_tar(
    name = "engines_layer",
    srcs = glob(["_engines/**"]),
    strip_prefix = "_engines",
    package_dir = "/app/engines",
)

pkg_tar(
    name = "models_layer",
    srcs = glob(["_models/**"]),
    strip_prefix = "_models",
    package_dir = "/app/models",
)

oci_image(
    name = "image",
    base = "@base_image_repo_linux_amd64",
    tars = [
        ":app_layer",
        ":handler_layer",
        ":engines_layer",
        ":models_layer",
    ],
    entrypoint = [
        "/app/handler_with_deps",
    ],
)

oci_push(
    name = "push_image_to_dockerhub",
    image = ":image",
    repository = "index.docker.io/nightfury172/custom_flux_fs",
    remote_tags = ["latest"],
)