module(
    name = "flux_virtual_staging",
    version = "0.1.0",
)

bazel_dep(name = "rules_oci", version = "2.2.6")
bazel_dep(name = "rules_pkg", version = "1.0.1")
bazel_dep(name = "rules_python", version = "0.31.0")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

oci.pull(
    name = "base_image_repo",
    image = "nvcr.io/nvidia/pytorch:24.11-py3",
    platforms = ["linux/amd64"],
)

use_repo(
    oci,
    "base_image_repo_linux_amd64",
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")

pip.parse(
    name = "pip", 
    requirements_lock = "//:requirements.lock",
    requirements_txt = "//:requirements.txt", 
)

use_repo(pip, "pip")